version: '3.8'

services:
  postgres:
    image: postgres:15.2-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - todo-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    networks:
      - networknestjs

  nestjs-training:
    build: ./
    image: node:18-alpine
    ports:
      - 8080:8080
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    env_file:
      - .env.development
    depends_on:
      - postgres
    networks:
      - networknestjs

networks:
  networknestjs:
    driver: bridge

volumes:
  todo-postgres-data: