version: '3.8'

services:
  postgres:
    image: postgres:15.2-alpine
    restart: always
    ports:
      - '${FORWARD_POSTGRES_PORT:-5432}:5432'
    volumes:
      - 'nestjs-training-postgres-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    networks:
      - networknestjs

  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'nestjs-training-redis-data:/data'
    networks:
      - networknestjs
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

  nestjs-training:
    build: ./
    image: node:18-alpine
    ports:
      - 8080:8080
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    env_file:
      - .env.development
    depends_on:
      - postgres
      - redis
    networks:
      - networknestjs

networks:
  networknestjs:
    driver: bridge

volumes:
  nestjs-training-postgres-data:
    driver: local
  nestjs-training-redis-data:
    driver: local